/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Game_Model;
import javax.swing.JButton;

/**
 *  Representa el menu principal de la palicacion
 * @author DilanU
 */
public class Game_View_Menu1 extends javax.swing.JPanel 
{
    // Variables declaration - do not modify                     
    private javax.swing.JButton exit;
    private javax.swing.JButton kColor;
    private javax.swing.JButton mines;
    private javax.swing.JLabel tittle;
    // End of variables declaration     

    /**
     * Creates new form Game_view_menu1
     */
    public Game_View_Menu1() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mines = new javax.swing.JButton();
        kColor = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        tittle = new javax.swing.JLabel();
        
        
        tittle.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("MinesWipper");
        tittle.setBounds(0, 0, 200, 50);

        
        mines.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        mines.setName("MinesWipper");
        mines.setText("MinesWipper");
        mines.setBounds(0, 100, 200, 50);

        kColor.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        kColor.setName("K-Color");
        kColor.setText("K-Color");
        kColor.setBounds(0, 200, 200, 50);

        exit.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        exit.setName("Exit");
        exit.setText("Exit");
        exit.setBounds(0, 300, 200, 50);


        this.setSize( Game_Model.WIDTH, Game_Model.HEIGHT);
        this.setLayout(null);
        this.add(this.tittle);
        this.add(this.mines);
        this.add(this.kColor);
        this.add(this.exit);
    }// </editor-fold>                        


    /**
     * Devuelve el boton para salir
     * @return boton para salir
     */
    public JButton getExit() {
        return exit;
    }
    
    
    /**
     * Devuelve el boton del KColor
     * @return boton del KColor
     */
    public JButton getkColor() {
        return kColor;
    }

    
    /**
     * Devuelve el boton de mineswipper
     * @return boton de mineswipper
     */
    public JButton getMines() {
        return mines;
    }
} // fin de Game_View_Menu1
