/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Game_Model;
import javax.swing.JButton;

/**
 *
 * @author DilanU
 */
public class Game_View_Menu3 extends javax.swing.JPanel {

    // Variables declaration - do not modify                     
    private javax.swing.JButton easy;
    private javax.swing.JButton hard;
    private javax.swing.JButton medium;
    private javax.swing.JLabel tittle;
    // End of variables declaration    
    
    
    /**
     * Creates new form Game_view_Menu3
     */
    public Game_View_Menu3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tittle = new javax.swing.JLabel();
        easy = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        hard = new javax.swing.JButton();

        tittle.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("MinesWipper");
        tittle.setBounds(0, 0, 200, 50);

        easy.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        easy.setName("Easy");
        easy.setText("Easy");
        easy.setBounds(0, 100, 200, 50);

        medium.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        medium.setName("Medium");
        medium.setText("Medium");
        medium.setBounds(0, 200, 200, 50);


        hard.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        hard.setName("Hard");
        hard.setText("Hard");
        hard.setBounds(0, 300, 200, 50);

        this.setSize( Game_Model.WIDTH, Game_Model.HEIGHT);
        this.setLayout(null);
        this.add(this.tittle);
        this.add(this.easy);
        this.add(this.medium);
        this.add(this.hard);
    }// </editor-fold>                                                     


               

    public JButton getEasy() {
        return easy;
    }

    public JButton getHard() {
        return hard;
    }

    public JButton getMedium() {
        return medium;
    }

    
    

}
