/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Game_Model;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 * Representa un submenu en la aplicacion
 * @author DilanU
 */
public class Game_View_Menu2 extends javax.swing.JPanel {
                   
    private javax.swing.JButton hexagon;
    private javax.swing.JButton menu;
    private javax.swing.JButton square;
   
    /**
     * Creates new form Game_view_menu2
     */
    public Game_View_Menu2() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">   
    
    private void initComponents() {

        square = new javax.swing.JButton();
        hexagon = new javax.swing.JButton();
        menu = new javax.swing.JButton();

        square.setName("Square");
        square.setBounds(170, 230, 254, 94);
        square.setMargin(new Insets(0, 0, 0, 0));
        square.setIcon(new ImageIcon(this.getClass().getResource("/Images/boton3.png")));
        
        hexagon.setName("Hexagon");
        hexagon.setBounds(170, 345, 254, 94);
        hexagon.setIcon(new ImageIcon(this.getClass().getResource("/Images/boton4.png")));
       
        menu.setName("Menu");
        menu.setBounds(480, 470, 100, 100);
        menu.setIcon(new ImageIcon(this.getClass().getResource("/Images/volver1.png")));
        menu.setOpaque(false);
        menu.setContentAreaFilled(false);
        menu.setBorderPainted(false);

        this.setSize( Game_Model.WIDTH, Game_Model.HEIGHT);
        this.setLayout(null);
        this.add(this.square);
        this.add(this.hexagon);
        this.add(this.menu);
        
    }// </editor-fold>                                                      


    /**
     * Devuelve el boton para el modo hexagon
     * @return boton de modo hexagon
     */
    public JButton getHexagon() {
        return hexagon;
    }
    
    
    /**
     * Devuelve el boton del menu principal
     * @return boton del menu principal
     */
    public JButton getMenu() {
        return menu;
    }
    
    
    /**
     * Devuelve el boton del modo tradicional
     * @return boton del modo tradicional
     */
    public JButton getSquare() {
       
        return square;
    }
    
     @Override
    public void paint(Graphics g) {
        
        g.drawImage( new ImageIcon(getClass().getResource("/Images/fondo2.png")).getImage(), 0, 0, getWidth(), getHeight(),
                        this);
 
        setOpaque(false);
        super.paint(g); //To change body of generated methods, choose Tools | Templates.    
    }
    
} // fin de Game_View_Menu2
