/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Game_Model;
import javax.swing.JButton;

/**
 * Representa un submenu en la aplicacion
 * @author DilanU
 */
public class Game_View_Menu2 extends javax.swing.JPanel {

    // Variables declaration - do not modify                     
    private javax.swing.JButton hexagon;
    private javax.swing.JButton menu;
    private javax.swing.JButton square;
    private javax.swing.JLabel tittle;
    // End of variables declaration   
    
    
    /**
     * Creates new form Game_view_menu2
     */
    public Game_View_Menu2() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tittle = new javax.swing.JLabel();
        square = new javax.swing.JButton();
        hexagon = new javax.swing.JButton();
        menu = new javax.swing.JButton();

        tittle.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("MinesWipper");
        tittle.setBounds(0, 0, 200, 50);

        square.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        square.setName("Square");
        square.setText("Square");
        square.setBounds(0, 100, 200, 50);


        hexagon.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        hexagon.setName("Hexagon");
        hexagon.setText("Hexagon");
        hexagon.setBounds(0, 200, 200, 50);
        
        menu.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        menu.setName("Menu");
        menu.setText("Menu");
        menu.setBounds(0, 300, 200, 50);

        this.setSize( Game_Model.WIDTH, Game_Model.HEIGHT);
        this.setLayout(null);
        this.add(this.tittle);
        this.add(this.square);
        this.add(this.hexagon);
        this.add(this.menu);
    }// </editor-fold>                                                      


    /**
     * Devuelve el boton para el modo hexagon
     * @return boton de modo hexagon
     */
    public JButton getHexagon() {
        return hexagon;
    }
    
    
    /**
     * Devuelve el boton del menu principal
     * @return boton del menu principal
     */
    public JButton getMenu() {
        return menu;
    }
    
    
    /**
     * Devuelve el boton del modo tradicional
     * @return boton del modo tradicional
     */
    public JButton getSquare() {
       
        return square;
    }
} // fin de Game_View_Menu2
