/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Game_Model;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author DilanU
 */
public class Game_View_Menu3 extends javax.swing.JPanel {

    // Variables declaration - do not modify                     
    private javax.swing.JButton easy;
    private javax.swing.JButton hard;
    private javax.swing.JButton medium;
    private javax.swing.JLabel tittle;
    // End of variables declaration    
    
    
    /**
     * Creates new form Game_view_Menu3
     */
    public Game_View_Menu3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        easy = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        hard = new javax.swing.JButton();
        
        easy.setName("Easy");
        easy.setBounds(170, 165, 254, 74);
        easy.setMargin(new Insets(0, 0, 0, 0));
        easy.setIcon(new ImageIcon(getClass().getResource("/Images/Boton5.png")));

        medium.setName("Medium");
        medium.setBounds(170, 255, 254, 74);
        medium.setMargin(new Insets(0, 0, 0, 0));
        medium.setIcon(new ImageIcon(getClass().getResource("/Images/Boton6.png")));
        
        hard.setName("Hard");
        hard.setBounds(170, 345, 254, 74);
        hard.setMargin(new Insets(0, 0, 0, 0));
        hard.setIcon(new ImageIcon(getClass().getResource("/Images/Boton7.png")));

        this.setSize( Game_Model.WIDTH, Game_Model.HEIGHT);
        this.setLayout(null);
        this.add(this.easy);
        this.add(this.medium);
        this.add(this.hard);
        
    }// </editor-fold>                                                     


               

    public JButton getEasy() {
        return easy;
    }

    public JButton getHard() {
        return hard;
    }

    public JButton getMedium() {
        return medium;
    }

    @Override
    public void paint(Graphics g) {
        
        g.drawImage( new ImageIcon(getClass().getResource("/Images/fondo3.png")).getImage(), 0, 0, getWidth(), getHeight(),
                        this);
 
        setOpaque(false);
        super.paint(g); //To change body of generated methods, choose Tools | Templates.    
    }
    

}
