/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *  Representa el menu principal de la palicacion
 * @author DilanU
 */
public class Game_View_Menu1 extends javax.swing.JPanel {

    /**
     * Creates new form Game_view_menu1
     */
    public Game_View_Menu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mines = new javax.swing.JButton();
        kColor = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        tittle = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 600));

        mines.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        mines.setText("MinesWipper");

        kColor.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        kColor.setText("K-Color");

        exit.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        exit.setText("Exit");

        tittle.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("MinesWipper");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kColor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mines, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mines, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(kColor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton kColor;
    private javax.swing.JButton mines;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables

    /**
     * Devuelve el boton para salir
     * @return boton para salir
     */
    public JButton getExit() {
        return exit;
    }
    
    
    /**
     * Devuelve el boton del KColor
     * @return boton del KColor
     */
    public JButton getkColor() {
        return kColor;
    }

    
    /**
     * Devuelve el boton de mineswipper
     * @return boton de mineswipper
     */
    public JButton getMines() {
        return mines;
    }
} // fin de Game_View_Menu1